config/routes.rb
Swift::Application.routes.draw do
  
  resources :artists, :only => [:show]
  resources :songs, :only => [:show]

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  resources :beats, :only => [:index, :show, :new, :create, :destroy]

  get "home/index"

  root :to => "beats#index"

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
 

  has_and_belongs_to_many :songs
end

app/models/beat.rb
class Beat < ActiveRecord::Base
  belongs_to :user
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :artists
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :username, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, :presence => true,
  	    	       :length => { :within => 3..50 },
		       :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
  	    	       :confirmation => true,
  	    	       :length => { :within => 6..40 }
  validates :email, :presence => true,
  	    	    :format => { :with => email_regex },
		    :uniqueness => { :case_sensitive => false }

  before_save :encrypt_password

  #Return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(username, submitted_password)
    user = find_by_username(username)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  has_many :beats

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def new
  end

end

app/controllers/beats_controller.rb
class BeatsController < ApplicationController
  # GET /beats
  # GET /beats.xml
  def index
    @beats = Beat.all
    @beats.sort! { |a,b| b.created_at <=> a.created_at }
    @beat = Beat.new

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @beats }
    end

  end

  # GET /beats/1
  # GET /beats/1.xml
  def show
    @beat = Beat.find(params[:id])    

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @beat }
    end
  end

  # POST /beats
  # POST /beats.xml
  def create
    @user = User.find_by_id(current_user)
    
    if @user.nil?
      flash[:error] = "Please sign in to share your music"
      redirect_to signin_path
    else
      #@beat = @user.beats.create(params[:beat])
            
      
      respond_to do |format|
        if @user.beats.create!(params[:beat])
          format.html { redirect_to(beats_path, :notice => 'Beat was successfully created.') }
          format.xml  { render :xml => @beat, :status => :created, :location => @beat }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @beat.errors, :status => :unprocessable_entity }
	end     
      end
    end
  end

  # DELETE /beats/1
  # DELETE /beats/1.xml
  def destroy
    @beat = Beat.find(params[:id])
    @beat.destroy

    respond_to do |format|
      format.html { redirect_to(beats_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:username], params[:session][:password])

    if user.nil?
      flash.now[:error] = "Invalid username/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @title = @user.username
  end

  def new
    @user = User.new
    @title = "Sign up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/beats_helper.rb
module BeatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end  

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/beats/_feed_beat.html.erb
<tr>
  <td><%= link_to User.find(feed_beat.user).username, feed_beat.user %> is listening to <%= link_to Song.find(feed_beat.song_id).name, Song.find(feed_beat.song_id) %> by <%= link_to Artist.find(feed_beat.artist_id).name, Artist.find(feed_beat.artist_id) %></td>
</tr>
<tr>
  <td><%= link_to 'Show', feed_beat %></td>
  <td><%= link_to 'Hide', feed_beat, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>

app/views/beats/_form.html.erb
<%= form_for(@beat) do |f| %>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :song %><br />
    <%= f.text_field :song %>
  </div>
  <div class="actions">
    <%= f.submit "Swift" %>
  </div>
<% end %>

app/views/beats/index.html.erb
<h1>Listing beats</h1>

<h2>What are you listening to?</h2>
<%= render 'form' %>

<table>
  <tr>
    <th>Most Recent</th>
    <th></th>
  </tr>
  <%= render :partial => "beats/feed_beat",
             :collection => @beats %>
</table>

<br />

app/views/beats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Artist:</b>
  <%= @beat.artist %>
</p>

<p>
  <b>Song:</b>
  <%= @beat.song %>
</p>

<p>
  <b>User:</b>
  <%= @beat.user %>
</p>


<%= link_to 'Edit', edit_beat_path(@beat) %> |
<%= link_to 'Back', beats_path %>

app/views/home/index.html.erb
<h1>Swift</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= link_to 'Beats', beats_path %>

app/views/layouts/_header.html.erb
<header>
  
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Profile", current_user  %></li>
      <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign In", signin_path %></li>
      <li><%= link_to "Sign Up Now!", signup_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swift</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <%= render 'layouts/header' %>
  <h1><%= @title %></h1>

  <section>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </section>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Create Account" %>
  </div>
<% end %>

app/views/users/show.html.erb
wheee

<%= link_to 'Back', beats_path %>